version: '3.8'

services:
  postgres:
    container_name: postgres_db_cdn
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: mi_usuario
      POSTGRES_PASSWORD: mi_contraseña
      POSTGRES_DB: mi_base_de_datos
    volumes:
      - data:/var/lib/postgresql/data

  redis:
    container_name: redis_cdn
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  data:
    driver: local
  redis_data:
    driver: local
